services:
  # PostgreSQL database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: robo_advisory
    ports:
      - "5432:5432"
    networks:
      - vpc-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  decisional-node:
    build:
      context: ./decisional-node
      dockerfile: Dockerfile
    env_file:
      - .env-decisional-node
    volumes:
      - ./decisional-node:/app
    ports:
      - "9090:9090"  # metrics
    networks:
      - vpc-network
    depends_on:
      - db
      - rabbitmq

  operational-node:
    build:
      context: ./operational-node
      dockerfile: Dockerfile.dev 
    ports:
      - "8081:8081"
    env_file:
      - .env-operational-node
    depends_on:
      - db
      - rabbitmq
    networks:
      - vpc-network

  # # frontend
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./frontend/Dockerfile.dev
  #   ports:
  #     - "3000:80"
  #   networks:
  #     - vpc-network
  #   depends_on:
  #     - operational-node

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    networks:
      - vpc-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP protocol port 
      - "15672:15672" # management UI
    networks:
      - vpc-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  vpc-network:
    driver: bridge # simulate VPC

volumes:
  pgdata:
  rabbitmq_data: