services:
  # PostgreSQL database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: robo_advisory
    ports:
      - "5432:5432"
    networks:
      - vpc-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Compute node
  python-engine:
    build: ./python-node
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://admin:pass@db:5432/robo_advisory
      - PYTHONUNBUFFERED=1
    networks:
      - vpc-network
    depends_on:
      - db

  # Operational node
  go-backend:
    build: ./go-node
    ports:
      - "8081:8080" # where the app will run
    depends_on:
      - db
      - python-engine
    networks:
      - vpc-network

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    networks:
      - vpc-network

networks:
  vpc-network:
    driver: bridge # simulate VPC

volumes:
  pgdata: