# no Service needed, Decisional node only makes outbound connections (to RabbitMQ and Supabase)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: decisional-node
  namespace: investpilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decisional-node
  template:
    metadata:
      labels:
        app: decisional-node
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-worker-2
      containers:
        - name: decisional-node
          image: ghcr.io/andreiopran/investpilot-decisional-node:latest
          envFrom:
            - secretRef:
                name: python-secrets
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
