package router

import (
	"github.com/gin-gonic/gin"

	"github.com/andreiOpran/licenta/operational-node/internal/database"
	"github.com/andreiOpran/licenta/operational-node/internal/handlers"
	"github.com/andreiOpran/licenta/operational-node/internal/middleware"
	"github.com/andreiOpran/licenta/operational-node/internal/repositories"
	"github.com/andreiOpran/licenta/operational-node/internal/services"
)

// SetupRoutes registers all HTTP endpoints and maps them to handler functions
func SetupRoutes(r *gin.Engine) {
	// apply global middlewares
	r.Use(middleware.CORSMiddleware())
	r.Use(middleware.IPRateLimiter())
	r.Use(middleware.SecurityHeadersMiddleware())

	// init repositories
	authRepo := repositories.NewAuthRepository(database.DB)
	userRepo := repositories.NewUserRepository(database.DB)
	portfolioRepo := repositories.NewPortfolioRepository(database.DB)
	transactionRepo := repositories.NewTransactionRepository(database.DB)
	forecastRepo := repositories.NewForecastRepository(database.DB)
	rebalanceRepo := repositories.NewRebalanceRepository(database.DB)

	// init services with repository deps
	authService := services.NewAuthService(authRepo)
	userService := services.NewUserService(userRepo)
	securityService := services.NewSecurityService(userRepo)
	portfolioService := services.NewPortfolioService(portfolioRepo, userRepo)
	transactionService := services.NewTransactionService(transactionRepo)
	onboardingService := services.NewOnboardingService(userRepo)
	forecastService := services.NewForecastService(forecastRepo, portfolioRepo)
	stripeService := services.NewStripeService()
	dataPipelineService := services.NewDataPipelineService()
	rebalanceService := services.NewRebalanceService(rebalanceRepo, userRepo)

	// init handlers with service deps
	authHandler := handlers.NewAuthHandler(authService)
	userHandler := handlers.NewUserHandler(userService)
	securityHandler := handlers.NewSecurityHandler(securityService)
	portfolioHandler := handlers.NewPortfolioHandler(portfolioService)
	transactionHandler := handlers.NewTransactionHandler(transactionService)
	onboardingHandler := handlers.NewOnboardingHandler(onboardingService)
	forecastHandler := handlers.NewForecastHandler(forecastService)
	stripeHandler := handlers.NewStripeHandler(stripeService, userService)
	dataPipelineHandler := handlers.NewDataPipelineHandler(dataPipelineService)
	cronTriggerHandler := handlers.NewCronTriggerHandler(rebalanceService)

	// standalone routes (no db required)
	r.GET("/ping", handlers.PingHandler)
	r.GET("/status", handlers.StatusHandler)
	r.GET("/test-email", handlers.TestEmailHandler)

	// Internal endpoints triggered by Kubernetes CronJobs or ENABLE_CRON=false local dev curl
	internal := r.Group("/api/v1/internal")
	internal.Use(middleware.InternalAuth())
	{
		internal.POST("/pipeline/daily", dataPipelineHandler.RunDataPipeline)
		internal.POST("/pipeline/intraday", dataPipelineHandler.RunIntradayPipeline)
		internal.POST("/rebalance", cronTriggerHandler.RunRebalance)
		internal.POST("/cleanup", cronTriggerHandler.RunCleanup)
	}

	v1 := r.Group("/api/v1")
	{
		v1.POST("/simulate-investment", handlers.SimulateInvestmentHandler)

		v1.POST("/register", authHandler.RegisterHandler)
		v1.GET("/verify-email", authHandler.VerifyEmailHandler)
		v1.POST("/login", authHandler.LoginHandler)
		v1.POST("/logout", authHandler.LogoutHandler)
		v1.POST("/verify-2fa", authHandler.Verify2FAHandler)
		v1.POST("/refresh-token", authHandler.RefreshTokenHandler)
		v1.POST("/forgot-password", authHandler.ForgotPasswordHandler)
		v1.POST("/reset-password", authHandler.ResetPasswordHandler)
		v1.POST("/webhook/stripe", stripeHandler.WebhookHandler)

		protected := v1.Group("/", middleware.AuthMiddleware())
		{
			protected.GET("/user", userHandler.GetUserHandler)
			protected.PUT("/user/profile", userHandler.UpdateProfileHandler)
			protected.GET("/2fa/setup", securityHandler.Setup2FAHandler)
			protected.POST("/2fa/enable", securityHandler.Enable2FAHandler)
			protected.GET("/onboarding/questions", onboardingHandler.GetQuestionsHandler)
			protected.POST("/onboarding/submit", onboardingHandler.SubmitHandler)
			protected.POST("/deposit", userHandler.DepositHandler)
			protected.POST("/invest", portfolioHandler.InvestHandler)
			protected.POST("/sell", portfolioHandler.SellHandler)
			protected.POST("/deposit/intent", stripeHandler.CreateIntentHandler)
			protected.POST("/cashout", userHandler.CashoutHandler)
			protected.GET("/portfolio", portfolioHandler.GetPortfolioSummaryHandler)
			protected.GET("/portfolio/history", portfolioHandler.GetPortfolioHistoryHandler)
			protected.GET("/transactions", transactionHandler.GetTransactionsHandler)
			protected.POST("/forecast", forecastHandler.RequestForecastHandler)
			protected.GET("/forecast/status/:task_id", forecastHandler.GetForecastStatusHandler)
		}
	}

	// serve static assets generated by vite
	r.Static("/assets", "../frontend/dist/assets")
	r.StaticFile("/vite.svg", "../frontend/dist/vite.svg")

	// catch-all for client-side routing
	r.NoRoute(handlers.SPAFallbackHandler("../frontend/dist/index.html"))
}
