package router

import (
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"

	"github.com/andreiOpran/licenta/operational-node/internal/database"
	"github.com/andreiOpran/licenta/operational-node/internal/handlers"
	"github.com/andreiOpran/licenta/operational-node/internal/middleware"
	"github.com/andreiOpran/licenta/operational-node/internal/repositories"
	"github.com/andreiOpran/licenta/operational-node/internal/services"
)

// SetupRoutes registers all HTTP endpoints and maps them to handler functions
func SetupRoutes(r *gin.Engine) {
	// apply global middlewares
	r.Use(middleware.IPRateLimiter())
	r.Use(middleware.CORSMiddleware())
	r.Use(middleware.SecurityHeadersMiddleware())

	// init repositories
	authRepo := repositories.NewAuthRepository(database.DB)
	userRepo := repositories.NewUserRepository(database.DB)
	portfolioRepo := repositories.NewPortfolioRepository(database.DB)
	forecastRepo := repositories.NewForecastRepository(database.DB)
	rebalanceRepo := repositories.NewRebalanceRepository(database.DB) // for debug endpoint

	// init services with repository deps
	authService := services.NewAuthService(authRepo)
	userService := services.NewUserService(userRepo)
	securityService := services.NewSecurityService(userRepo)
	portfolioService := services.NewPortfolioService(portfolioRepo, userRepo)
	forecastService := services.NewForecastService(forecastRepo, portfolioRepo)
	stripeService := services.NewStripeService()
	rebalanceService := services.NewRebalanceService(rebalanceRepo, userRepo) // for debug endpoint
	dataPipelineService := services.NewDataPipelineService()                  // for debug endpoint

	// init handlers with service deps
	authHandler := handlers.NewAuthHandler(authService)
	userHandler := handlers.NewUserHandler(userService)
	securityHandler := handlers.NewSecurityHandler(securityService)
	portfolioHandler := handlers.NewPortfolioHandler(portfolioService)
	forecastHandler := handlers.NewForecastHandler(forecastService)
	stripeHandler := handlers.NewStripeHandler(stripeService, userService)
	rebalanceHandler := handlers.NewRebalanceHandler(rebalanceService)          // for debug endpoint
	dataPipelineHandler := handlers.NewDataPipelineHandler(dataPipelineService) // for debug endpoint

	// standalone routes (no db required)
	r.GET("/ping", handlers.PingHandler)
	r.GET("/status", handlers.StatusHandler)
	r.GET("/test-email", handlers.TestEmailHandler)

	debug := r.Group("/debug")
	{
		debug.POST("/data-pipeline", dataPipelineHandler.RunDataPipeline)
		debug.POST("/rebalance", rebalanceHandler.Rebalance)
	}

	v1 := r.Group("/api/v1")
	{
		v1.POST("/simulate-investment", handlers.SimulateInvestmentHandler)

		v1.POST("/register", authHandler.RegisterHandler)
		v1.GET("/verify-email", authHandler.VerifyEmailHandler)
		v1.POST("/login", authHandler.LoginHandler)
		v1.POST("/logout", authHandler.LogoutHandler)
		v1.POST("/verify-2fa", authHandler.Verify2FAHandler)
		v1.POST("/refresh-token", authHandler.RefreshTokenHandler)
		v1.POST("/forgot-password", authHandler.ForgotPasswordHandler)
		v1.POST("/reset-password", authHandler.ResetPasswordHandler)
		v1.POST("/webhook/stripe", stripeHandler.WebhookHandler)

		protected := v1.Group("/", middleware.AuthMiddleware())
		{
			protected.GET("/user", userHandler.GetUserHandler)
			protected.PUT("/user/profile", userHandler.UpdateProfileHandler)
			protected.GET("/2fa/setup", securityHandler.Setup2FAHandler)
			protected.POST("/2fa/enable", securityHandler.Enable2FAHandler)
			protected.POST("/deposit", userHandler.DepositHandler)
			protected.POST("/invest", portfolioHandler.InvestHandler)
			protected.POST("/deposit/intent", stripeHandler.CreateIntentHandler)
			protected.POST("/cashout", userHandler.CashoutHandler)
			protected.POST("/forecast", forecastHandler.RequestForecastHandler)
			protected.GET("/forecast/status/:task_id", forecastHandler.GetForecastStatusHandler)
		}
	}

	// serve static assets generated by vite
	r.Static("/assets", "../frontend/dist/assets")
	r.StaticFile("/vite.svg", "../frontend/dist/vite.svg")

	// catch-all for client-side routing
	r.NoRoute(func(c *gin.Context) {
		// if request was meant for API endpoint, return 404 json
		if strings.HasPrefix(c.Request.URL.Path, "/api/") {
			c.JSON(http.StatusNotFound, gin.H{"error": "API route not found"})
			return
		}

		// otherwise, serve SPA index.html so React Router can take over
		c.File("../frontend/dist/index.html")
	})
}
